# Generated by Django 5.0.4 on 2024-04-29 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('contact_person_name', models.CharField(max_length=100, verbose_name='contact person name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('mobile_number', models.CharField(blank=True, max_length=15, verbose_name='mobile number')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='brand logo')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook link')),
                ('twitter_link', models.URLField(blank=True, verbose_name='Twitter link')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile_number', models.CharField(blank=True, max_length=15, verbose_name='mobile number')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='birthday date')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='language')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='category')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('postcode', models.CharField(blank=True, max_length=6, verbose_name='postcode')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook link')),
                ('twitter_link', models.URLField(blank=True, verbose_name='Twitter link')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram link')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='profile picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
