# Generated by Django 5.0.4 on 2024-04-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_agencyprofile_influencerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyprofile',
            name='contact_email',
        ),
    ]
