# Generated by Django 5.0.4 on 2024-05-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_locationinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationInfo',
        ),
    ]
