# Generated by Django 5.0.4 on 2024-05-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
