# Generated by Django 5.0.4 on 2024-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_orders_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('reported', 'Reported'), ('canceled', 'Canceled'), ('job_done', 'Job Done')], default='pending', max_length=20),
        ),
    ]
