# Generated by Django 5.0.4 on 2024-05-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_orders_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
