# Generated by Django 5.0.4 on 2024-04-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
    ]
